### POST request to create a new rating
POST http://localhost:8083/api/ratings
Content-Type: application/json

{
  "userId": "92091cab-f04f-4b25-81b5-71150ba8ccc4",
  "hotelId": "1439ce10-2ace-48ab-8ad0-9dbd2874e418",
  "feedback": " It is a palace with great hospitality and wonderful ambience.",
  "rating": 9
}