### POST request to create a new rating
POST http://localhost:8083/api/ratings
Content-Type: application/json

{
  "userId": "92091cab-f04f-4b25-81b5-71150ba8ccc4",
  "hotelId": "69e5cd68-e0ca-4221-8fdf-5da9f420338c",
  "feedback": " This is a good place to stay",
  "rating": 10
}