### GET request to example server
POST http://localhost:8082/api/hotels
Content-Type: application/json

{
  "name": "Seesh Mahal",
  "address": "Chennai",
  "about": "This is the Reception centre to my Brother's wedding"
}
###